// src/components/Footer.svelte
<div class="bg-gray-100 dark:bg-slate-800 dark:text-white py-8">
	<div class="ct text-center">
        <p>&copy; 2020-{new Date().getFullYear()} GambitProfit. Proudly powered by <a href="https://svelte.dev" target="_blank" rel="noopener">Svelte</a> and <a href="https://djangoproject.com" target="_blank" rel="noopener">Django</a>.</p>
    </div>
</div>

// frontend/components/Footer.vue
<template>
  <v-footer
    padless
    class="mt-5"
  >
    <v-card
      class="flex"
      flat
      tile
    >
<!--      <v-card-title class="blue white&#45;&#45;text">-->

<!--      </v-card-title>-->
      <v-card-text class="teal white--text py-5 text-center">
        &copy; 2020-{{ new Date().getFullYear() }} <strong>GambitProfit</strong> - Made with
        <v-icon class="red--text">mdi-heart</v-icon>
        by Unixfy.
        <br/>
        Proudly powered by <a href="https://nuxtjs.org" target="_blank" rel="noopener" style="color:white;">Nuxt.js</a> and <a
        href="https://strapi.io" target="_blank" rel="noopener" style="color:white;">Strapi</a>.
      </v-card-text>
    </v-card>
  </v-footer>
</template>
